# Generated by Django 4.1.2 on 2022-12-22 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_follow_followed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follow',
            name='followed',
            field=models.ManyToManyField(blank=True, related_name='follows', to='app.profile'),
        ),
    ]
