# Generated by Django 4.1.2 on 2022-11-29 22:29

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_posts_delete_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('text_content', models.TextField(max_length=280)),
                ('posted_at', models.DateTimeField(default=datetime.datetime(2022, 11, 29, 19, 29, 7, 953859))),
                ('likes', models.IntegerField(default=0)),
                ('reposts', models.IntegerField(default=0)),
                ('coments', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='Posts',
        ),
    ]
