# Generated by Django 4.1.2 on 2022-12-12 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_post_posted_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('who_is_following', models.CharField(max_length=100)),
                ('who_is_being_followed', models.CharField(max_length=100)),
            ],
        ),
    ]
