# Generated by Django 4.1.2 on 2022-12-14 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='who_is_being_liked',
            new_name='post_being_liked',
        ),
    ]
